name: 'find-good-books'
channels:
  - conda-forge
dependencies:
  - python==3.12
  - ipykernel
  - pandas
  - numpy
  - duckdb
  - langchain
  - nltk
  - shiny
  - faiss-cpu
  - pip
  - pip:
    - dotenv
    - rank_bm25
    - langchain_community
    - langchain_huggingface
    - sentence_transformers


    